### ISSUE TITLE
Code reproducing figures from README

### ISSUE THREAD

**Issue by kudkudak** [tensorflow/kfac#13]
Thanks a lot for preparing this package! 

I got recently interested in KFAC and have been trying to reproduce the deep autoencoder experiment. Would it be possible to share code that reproduces the figures in the README?

**Comment by duckworthd** [comment]
Hi @kudkudak,

I believe those experiments are [here](https://github.com/tensorflow/kfac/tree/master/kfac/examples) in the `kfac/examples`. If memory serves, I processed the [log lines](https://github.com/tensorflow/kfac/blob/master/kfac/examples/convnet.py#L217-L218) in Python to make the plots.

Let me know if the examples fail to generate similar-looking plots?

**Comment by duckworthd** [comment]
I'm sorry, the contents of the `examples` folder are definitely _not_ the same as the ones in the plots! Code for those plots is still forthcoming.

If you're eager to reproduce sooner rather than later, the architecture is identical to the one published in [
Optimizing Neural Networks with Kronecker-factored Approximate Curvature](https://arxiv.org/abs/1503.05671)

**Comment by vikramtankasali** [comment]
Hi @kudkudak ,
 The code to reproduce the plots is [here](https://github.com/tensorflow/kfac/blob/master/kfac/examples/kfac_mnist_autoencoder_auto_damping.py).  There are couple of changes required to exactly reproduce the results. 
1) Change momentum=0.0, momentum_type='qmodel', learning_rate=1. when creating the `PeriodicInvCovUpdateKfacOpt `.
2) Batch size schedule: Change batch size in load_mnist to maximum batch size value in the schedule. and feed into the `batch_size` placeholder appropriate value from the schedule in every iteration.

**Comment by kudkudak** [comment]
Thanks a lot! :)
