### ISSUE TITLE
Is there any plan to port to this to Tensorflow 2

### ISSUE THREAD

**Issue by chakkeiwong** [tensorflow/kfac#38]
It will be great if this can be ported to TF2.

**Comment by james-martens** [comment]
Sorry, but there are no plans for this.  If someone in the OSS community wants to do it I would be happy to send them some pointers.  We have plans to release a version of K-FAC implemented in JAX in the coming months.

**Comment by james-martens** [comment]
I should add to this that K-FAC should work with any new versions of the TF library, as long as they are running in TF1 compatibility mode (i.e. with "import tensorflow.compat.v1 as tf" etc). In fact, this is the preferred way. Actually loading the 1.15 version of the library might not always be supported, due to breaking changes.
